import { Imovie } from "../models/movieT";


export let movieData: Array<Imovie> = [
  {
    adult: false,
    backdrop_path: '/gslT8t964rYXyqRcqrxFh77ikyb.jpg',
    genre_ids: [12, 878, 35],
    id: 640146,
    original_language: 'en',
    original_title: 'Ant-Man and the Wasp: Quantumania',
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    popularity: 711.057,
    poster_path: '/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg',
    release_date: '2023-02-15',
    title: 'Ant-Man and the Wasp: Quantumania',
    video: false,
    vote_average: 6.4,
    vote_count: 1077,
  },
  {
    adult: false,
    backdrop_path: '/32GH8Mi4GmTPIQyd6IW1FFrHWrj.jpg',
    genre_ids: [28],
    id: 965839,
    original_language: 'en',
    original_title: 'Lord of the Streets',
    overview:
      "When Jason Dyson refuses to make his prized fighter throw an MMA match, a notorious gangster collects his debt by killing the fighter and kidnapping Jason's daughter. Now he must train a prisoner to endure five consecutive underground fights to save her.",
    popularity: 678.731,
    poster_path: '/mbigXpUgVgLOacgxlyFfsLRFqxQ.jpg',
    release_date: '2022-04-22',
    title: '',
    video: false,
    vote_average: 5.2,
    vote_count: 47,
  },
  {
    adult: false,
    backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
    genre_ids: [28, 14, 878],
    id: 436270,
    original_language: 'en',
    original_title: 'Black Adam',
    overview:
      'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
    popularity: 675.827,
    poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
    release_date: '2022-10-19',
    title: 'Black Adam',
    video: false,
    vote_average: 7.1,
    vote_count: 4541,
  },
  {
    adult: true,
    backdrop_path: '/bvAMLx00BOr6vkSQWZscwGrPdGI.jpg',
    genre_ids: [53, 28, 18, 80],
    id: 1058949,
    original_language: 'en',
    original_title: 'Little Dixie',
    overview:
      'Erstwhile Special Forces operative Doc Alexander is asked to broker a truce with the Mexican drug cartel in secrecy. When Oklahoma Governor Richard Jeffs celebrates the execution of a high-ranking cartel member on TV, his Chief of Staff and Doc inform him about the peace he just ended. But it’s too late, as Cuco, the cartel’s hatchet man, has set his vengeful sights on Doc’s daughter Dixie.',
    popularity: 611.491,
    poster_path: '/cmWTZj9zzT9KFt3XyL0gssL7Ig8.jpg',
    release_date: '2023-02-03',
    title: 'Little Dixie',
    video: false,
    vote_average: 6.1,
    vote_count: 88,
  },
  {
    adult: false,
    backdrop_path: '/r7Dfg9aRZ78gJsmDlCirIIlNH3d.jpg',
    genre_ids: [18],
    id: 785084,
    original_language: 'en',
    original_title: 'The Whale',
    overview:
      'A reclusive English teacher suffering from severe obesity attempts to reconnect with his estranged teenage daughter for one last chance at redemption.',
    popularity: 577.407,
    poster_path: '/jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg',
    release_date: '2022-12-09',
    title: 'The Whale',
    video: false,
    vote_average: 8.1,
    vote_count: 1584,
  },
  {
    adult: true,
    backdrop_path: '/254iY5CzFzjnjkP0lUkLpOLvXar.jpg',
    genre_ids: [53, 18, 80],
    id: 881164,
    original_language: 'en',
    original_title: 'Boston Strangler',
    overview:
      'Reporters Loretta McLaughlin and Jean Cole bravely pursue the story of the Boston Strangler at great personal risk, putting their own lives on the line in their quest to uncover the truth.',
    popularity: 571.547,
    poster_path: '/oZJfw78ZyPmgNJ0YJ8070nKEF4Y.jpg',
    release_date: '2023-03-17',
    title: 'Boston Strangler',
    video: false,
    vote_average: 6.7,
    vote_count: 150,
  },
  {
    adult: false,
    backdrop_path: '/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg',
    genre_ids: [28, 10749, 35],
    id: 758009,
    original_language: 'en',
    original_title: 'Shotgun Wedding',
    overview:
      'Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save their loved ones—if they don’t kill each other first.',
    popularity: 580.742,
    poster_path: '/t79ozwWnwekO0ADIzsFP1E5SkvR.jpg',
    release_date: '2022-12-28',
    title: 'Shotgun Wedding',
    video: false,
    vote_average: 6.3,
    vote_count: 684,
  },
  {
    adult: false,
    backdrop_path: '/hlxduUs8y9icWGMzYCDLcYHEQ2u.jpg',
    genre_ids: [53, 18],
    id: 985939,
    original_language: 'en',
    original_title: 'Fall',
    overview:
      'For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights',
    popularity: 532.743,
    poster_path: '/v28T5F1IygM8vXWZIycfNEm3xcL.jpg',
    release_date: '2022-08-11',
    title: 'Fall',
    video: false,
    vote_average: 7.3,
    vote_count: 2591,
  },
  {
    adult: false,
    backdrop_path: '/v2LilmCylr3bL9TCZSj6syjowZh.jpg',
    genre_ids: [35, 18],
    id: 937278,
    original_language: 'en',
    original_title: 'A Man Called Otto',
    overview:
      'When a lively young family moves in next door, grumpy widower Otto Anderson meets his match in a quick-witted, pregnant woman named Marisol, leading to an unlikely friendship that turns his world upside down.',
    popularity: 591.802,
    poster_path: '/130H1gap9lFfiTF9iDrqNIkFvC9.jpg',
    release_date: '2022-12-28',
    title: 'A Man Called Otto',
    video: false,
    vote_average: 7.9,
    vote_count: 836,
  },
  {
    adult: true,
    backdrop_path: '/f1PSBBNYKuCjubTgHwFkPr5SidC.jpg',
    genre_ids: [16, 12, 10751, 14],
    id: 502356,
    original_language: 'en',
    original_title: 'The Super Mario Bros. Movie',
    overview:
      'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
    popularity: 578.624,
    poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
    release_date: '2023-03-30',
    title: 'The Super Mario Bros. Movie',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/af1tFYzzT2mHIy2l7nTIU8PWfak.jpg',
    genre_ids: [80, 18, 53],
    id: 842942,
    original_language: 'en',
    original_title: 'Bandit',
    overview:
      'After escaping a Michigan prison, a charming career criminal assumes a new identity in Canada and goes on to rob a record 59 banks and jewellery stores while being hunted by a rogue task force. Based on the story of The Flying Bandit.',
    popularity: 561.288,
    poster_path: '/yph9PAbmjYPvyvbeZvdYIhCZHEu.jpg',
    release_date: '2022-09-23',
    title: 'Bandit',
    video: false,
    vote_average: 6.1,
    vote_count: 130,
  },
  {
    adult: false,
    backdrop_path: '/r17jFHAemzcWPPtoO0UxjIX0xas.jpg',
    genre_ids: [28, 53, 80],
    id: 324552,
    original_language: 'en',
    original_title: 'John Wick: Chapter 2',
    overview:
      'John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.',
    popularity: 657.092,
    poster_path: '/hXWBc0ioZP3cN4zCu6SN3YHXZVO.jpg',
    release_date: '2017-02-08',
    title: 'John Wick: Chapter 2',
    video: false,
    vote_average: 7.3,
    vote_count: 11095,
  },
  {
    adult: false,
    backdrop_path: '/sp7MPK2K60LLd7A6zjHKsfgjFil.jpg',
    genre_ids: [27, 53],
    id: 296271,
    original_language: 'en',
    original_title: 'The Devil Conspiracy',
    overview:
      'The hottest biotech company in the world has discovered they can clone history’s most influential people from the dead. Now, they are auctioning clones of Michelangelo, Galileo, Vivaldi, and others for tens of millions of dollars to the world’s ultra-rich. But when they steal the Shroud of Turin and clone the DNA of Jesus Christ, all hell breaks loose.',
    popularity: 703.801,
    poster_path: '/1AWcMtUZjpkq4h52yDnNIp9FwEO.jpg',
    release_date: '2023-01-13',
    title: 'The Devil Conspiracy',
    video: false,
    vote_average: 5.9,
    vote_count: 26,
  },
  {
    adult: false,
    backdrop_path: '/vVpEOvdxVBP2aV166j5Xlvb5Cdc.jpg',
    genre_ids: [28, 53, 80],
    id: 458156,
    original_language: 'en',
    original_title: 'John Wick: Chapter 3 - Parabellum',
    overview:
      'Super-assassin John Wick returns with a $14 million price tag on his head and an army of bounty-hunting killers on his trail. After killing a member of the shadowy international assassin’s guild, the High Table, John Wick is excommunicado, but the world’s most ruthless hit men and women await his every turn.',
    popularity: 660.42,
    poster_path: '/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg',
    release_date: '2019-05-15',
    title: 'John Wick: Chapter 3 - Parabellum',
    video: false,
    vote_average: 7.4,
    vote_count: 8790,
  },
  {
    adult: false,
    backdrop_path: '/xnAi4BRoO3ZQ3wwxGn6UNoxQzDq.jpg',
    genre_ids: [80, 28],
    id: 823999,
    original_language: 'it',
    original_title: "Diabolik - Ginko all'attacco!",
    overview:
      "Diabolik nearly gets caught in Inspector Ginko's latest trap, leaving his partner in crime Eva Kant behind in the escape. Furious, Eva offers Ginko her help in capturing the King of Terror, but the former has to face the return of an old flame of his.",
    popularity: 527.561,
    poster_path: '/8QVbWBv94BAT9u1q9uJccwOxMzt.jpg',
    release_date: '2022-11-17',
    title: 'Diabolik - Ginko Attacks',
    video: false,
    vote_average: 5.7,
    vote_count: 108,
  },
  {
    adult: false,
    backdrop_path: '/44immBwzhDVyjn87b3x3l9mlhAD.jpg',
    genre_ids: [27, 9648, 53],
    id: 934433,
    original_language: 'en',
    original_title: 'Scream VI',
    overview:
      'Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.',
    popularity: 471.939,
    poster_path: '/aePBN8ffLCHoUXp8lkA5P29CXdx.jpg',
    release_date: '2023-03-08',
    title: 'Scream VI',
    video: false,
    vote_average: 7.4,
    vote_count: 375,
  },
  {
    adult: false,
    backdrop_path: '/AqhA7GXDEaP1spOWih195YzSPem.jpg',
    genre_ids: [16, 28, 12, 14, 53],
    id: 635302,
    original_language: 'ja',
    original_title: '劇場版「鬼滅の刃」無限列車編',
    overview:
      "Tanjiro Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyojuro Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
    popularity: 479.628,
    poster_path: '/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg',
    release_date: '2020-10-16',
    title: 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train',
    video: false,
    vote_average: 8.3,
    vote_count: 3006,
  },
  {
    adult: false,
    backdrop_path: '/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg',
    genre_ids: [28, 12, 14, 878],
    id: 19995,
    original_language: 'en',
    original_title: 'Avatar',
    overview:
      'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
    popularity: 498.87,
    poster_path: '/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg',
    release_date: '2009-12-15',
    title: 'Avatar',
    video: false,
    vote_average: 7.6,
    vote_count: 28695,
  },
  {
    adult: false,
    backdrop_path: '/sRfX2XPjyL7nRKVRKXVG6D0bVQI.jpg',
    genre_ids: [27, 53],
    id: 884184,
    original_language: 'en',
    original_title: 'Consecration',
    overview:
      "After the alleged suicide of her priest brother, Grace travels to the remote Scottish convent where he fell to his death. Distrusting the Church's account, she uncovers murder, sacrilege and a disturbing truth about herself.",
    popularity: 587.397,
    poster_path: '/yQTRmPzKAdLodknnPVtImm6FWPZ.jpg',
    release_date: '2023-02-09',
    title: 'Consecration',
    video: false,
    vote_average: 7,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: '/A2avUoNFstnBhAnHiogXQs4c9Bt.jpg',
    genre_ids: [18, 27, 9648],
    id: 772515,
    original_language: 'es',
    original_title: 'Huesera',
    overview:
      "Valeria's joy at becoming a first-time mother is quickly taken away when she's cursed by a sinister entity. As danger closes in, she's forced deeper into a chilling world of dark magic that threatens to consume her.",
    popularity: 417.787,
    poster_path: '/zgpj76z9byUgcWnxLDmtZ3XqfvN.jpg',
    release_date: '2023-02-10',
    title: 'Huesera: The Bone Woman',
    video: false,
    vote_average: 5.8,
    vote_count: 159,
  },
];

const anime = [
  {
    id: 1,
    title: 'Demon Slayer: Kimetsu no Yaiba',
    year: 2019,
    rating: 8.8,
    image:
      'https://www.themoviedb.org/t/p/w1280/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg',
    overview:
      'Tanjiro Kamado joins the Demon Slayer Corps after demons slaughter his family and curse his sister.',
  },
  {
    id: 2,
    title: 'Death Note',
    year: 2006,
    rating: 8.9,
    image:
      'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/qDhbGqjZ7yFwa7FMIzuiQTQMfEQ.jpg',
    overview:
      'A high school student discovers a notebook with deadly powers and sets out to rid the world of criminals.',
  },
  {
    id: 3,
    title: 'Naruto: Shippuden',
    year: 2007,
    rating: 8.7,
    image:
      'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/bBqEiQbbfyt4MWR3NhDZMbS4Wp8.jpg',
    overview:
      'Naruto Uzumaki continues his journey to become Hokage, facing powerful enemies and protecting his friends.',
  },
  {
    id: 4,
    title: 'Jujutsu Kaisen',
    year: 2020,
    rating: 8.6,
    image:
      'https://image.tmdb.org/t/p/w440_and_h660_face/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
    overview:
      'A boy swallows a cursed object and joins a school of sorcerers to fight deadly curses.',
  },
  {
    id: 5,
    title: 'One Punch Man',
    year: 2015,
    rating: 8.5,
    image:
      'https://image.tmdb.org/t/p/w440_and_h660_face/iE3s0lG5QVdEHOEZnoAxjmMtvne.jpg',
    overview:
      'Saitama is a superhero who can defeat any opponent with a single punch but struggles with boredom and purpose.',
  },
  {
    id: 6,
    title: 'My Hero Academia',
    year: 2016,
    rating: 8.4,
    image:
      'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/tTrI6PwqzxkgO3dvQ7BEKXM7SYR.jpg',
    overview:
      'In a world where most people have superpowers, a powerless boy dreams of becoming the greatest hero.',
  },
  {
    id: 7,
    title: 'Dragon Ball Z',
    year: 1989,
    rating: 8.5,
    image:
      'https://image.tmdb.org/t/p/w440_and_h660_face/6VKOfL6ihwTiB5Vibq6QTfzhxA6.jpg',
    overview:
      'Goku and his friends defend Earth from powerful foes in epic battles spanning the universe.',
  },
  {
    id: 8,
    title: 'Hunter x Hunter',
    year: 2011,
    rating: 9.0,
    image:
      'https://image.tmdb.org/t/p/w440_and_h660_face/ucpgmUR1h5Te1BYegKItoPjOeF7.jpg',
    overview:
      'Gon Freecss becomes a Hunter to find his missing father while facing dangerous adventures and enemies.',
  },
  {
    id: 9,
    title: 'Tokyo Ghoul',
    year: 2014,
    rating: 7.8,
    image:
      'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/1m4RlC9BTCbyY549TOdVQ5NRPcR.jpg',
    overview:
      'A college student is transformed into a half-ghoul after a deadly encounter and struggles to live between two worlds.',
  },
  {
    id: 10,
    title: 'Bleach: Thousand-Year Blood War',
    year: 2022,
    rating: 8.9,
    image:
      'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg',
    overview:
      'Ichigo Kurosaki returns to face the Quincy army in a war that will shake the Soul Society.',
  },
  {
    id: 11,
    title: 'Attack on Titan',
    year: 2013,
    rating: 9.0,
    image:
      'https://image.tmdb.org/t/p/w440_and_h660_face/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
    overview:
      'After humanity is nearly exterminated by giant creatures, survivors fight back against the terrifying Titans.',
  },
  {
    id: 12,
    title: 'Fullmetal Alchemist: Brotherhood',
    year: 2009,
    rating: 9.1,
    image:
      'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg',
    overview:
      'Two brothers use alchemy to restore their bodies after a failed ritual, uncovering deep government secrets.',
  },
];

const animeToMovies: Array<Imovie> = anime.map((a) => ({
  adult: false,
  backdrop_path: a.image,
  genre_ids: [16], 
  id: a.id,
  original_language: 'ja',
  original_title: a.title,
  overview: a.overview,
  popularity: 300, 
  poster_path: a.image,
  release_date: `${a.year}-01-01`,
  title: a.title,
  video: false,
  vote_average: a.rating,
  vote_count: 1000, 
}));

movieData = [...animeToMovies, ...movieData];
